apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
      - name: plex
        image: tccr.io/truecharts/plex:v1.40.0.7998-c29d46c0d@sha256:6d6e12d2388268b64ae0d0ec0cfee99293a17a6b67ef9a5ca8df02a1de4cdcf1
        securityContext:
          privileged: true
        ports:
        - containerPort: 32400
          name: web
        env:
        - name: PLEX_CLAIM
          value: "claim-REPLACE_WITH_YOUR_TOKEN"
        resources:
          limits:
            cpu: "4"
            memory: 8Gi
          requests:
            cpu: "2"
            memory: 4Gi
        volumeMounts:
        - name: config
          mountPath: /config
        - name: media
          mountPath: /data
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: plex-config
      - name: media
        persistentVolumeClaim:
          claimName: media-nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: media
spec:
  type: NodePort
  ports:
  - port: 32400
    targetPort: web
    nodePort: 32400
    name: web
  selector:
    app: plex
