apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - name: radarr
        image: tccr.io/truecharts/radarr:v5.2.4.8328@sha256:e715df7bcec954dc2e38f73ef4a6eda44cb8df8a4cd5a0deb901c50e69d3a0f8
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        ports:
        - containerPort: 7878
          name: web
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: "0.5"
            memory: 512Mi
        volumeMounts:
        - name: config
          mountPath: /config
        - name: media
          mountPath: /data
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: radarr-config
      - name: media
        persistentVolumeClaim:
          claimName: media-nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: media
spec:
  type: NodePort
  ports:
  - port: 7878
    targetPort: web
    nodePort: 30878
    name: web
  selector:
    app: radarr
