apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      containers:
      - name: sabnzbd
        image: tccr.io/truecharts/sabnzbd:v4.2.0@sha256:b7e1de35f8a10f6f1a16dc8d5ae6b2b78fd91f6c8b8f2591ab3f5c4a67d0aa81
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          runAsNonRoot: true
        ports:
        - containerPort: 8080
          name: web
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: "0.5"
            memory: 512Mi
        volumeMounts:
        - name: config
          mountPath: /config
          subPath: sabnzbd/config
        - name: media
          mountPath: /data/downloads
          subPath: downloads
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: media-nfs-pvc
      - name: media
        persistentVolumeClaim:
          claimName: media-nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
  namespace: media
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: web
    nodePort: 30080
    name: web
  selector:
    app: sabnzbd
