apiVersion: v1
kind: ServiceAccount
metadata:
  name: media-apps
  namespace: media
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: media-apps-role
  namespace: media
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: media-apps-rolebinding
  namespace: media
subjects:
- kind: ServiceAccount
  name: media-apps
  namespace: media
roleRef:
  kind: Role
  name: media-apps-role
  apiGroup: rbac.authorization.k8s.io
