apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jellyfin-movies
spec:
  capacity:
    storage: 1Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-static
  nfs:
    server: 192.168.0.90
    path: /volume1/media
  mountOptions:
    - nfsvers=4
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-movies
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  volumeName: pv-jellyfin-movies
  storageClassName: nfs-static
