apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
  labels:
    managed-by: gitops
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
# Enable monitoring for user workloads
# Docs: https://docs.openshift.com/container-platform/latest/monitoring/enabling-monitoring-for-user-defined-projects.html
data:
  config.yaml: |
    enableUserWorkload: true
