apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: homelab-argocd
  namespace: media
spec:
  server:
    route:
      enabled: true
  repo:
    mountsaferepositories: true
  rbac:
    defaultPolicy: 'role:readonly'
  ha:
    enabled: false
  applicationSet:
    enabled: true
  resourceTrackingMethod: annotation+label
  notifications:
    enabled: true
  sso:
    dex:
      openShiftOAuth: true
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 250m
          memory: 128Mi
  grafana:
    enabled: false
  prometheus:
    enabled: false
