apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-root
  namespace: media
spec:
  destination:
    namespace: media
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: applications
    repoURL: file:///tmp/local-repo
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
