apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: media
spec:
  destination:
    namespace: media
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: plex
    repoURL: https://charts.truecharts.org/
    targetRevision: 12.1.2
    helm:
      values: |
        image:
          repository: tccr.io/truecharts/plex
          tag: v1.40.0.7998-c29d46c0d@sha256:6d6e12d2388268b64ae0d0ec0cfee99293a17a6b67ef9a5ca8df02a1de4cdcf1

        service:
          main:
            type: NodePort
            ports:
              main:
                port: 32400
                nodePort: 32400

        plex:
          claimToken: "claim-REPLACE_WITH_YOUR_TOKEN"

        persistence:
          config:
            enabled: true
            type: pvc
            mountPath: /config
            existingClaim: plex-config
          media:
            enabled: true
            type: pvc
            mountPath: /data
            existingClaim: media-nfs-pvc
            
        resources:
          limits:
            cpu: 4000m
            memory: 8Gi
          requests:
            cpu: 2000m
            memory: 4Gi

        networkPolicy:
          enabled: false

        securityContext:
          container:
            runAsNonRoot: false
            readOnlyRootFilesystem: false
            runAsUser: 0
            runAsGroup: 0
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
