apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
  namespace: media
spec:
  destination:
    namespace: media
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/truecharts/charts.git
    targetRevision: master
    path: charts/stable/radarr
    helm:
      values: |
        image:
          repository: tccr.io/truecharts/radarr
          tag: v5.2.4.8328@sha256:e715df7bcec954dc2e38f73ef4a6eda44cb8df8a4cd5a0deb901c50e69d3a0f8

        service:
          main:
            type: NodePort
            ports:
              main:
                port: 7878
                nodePort: 30878

        persistence:
          config:
            enabled: true
            type: pvc
            mountPath: /config
            existingClaim: radarr-config
          media:
            enabled: true
            type: pvc
            mountPath: /data
            existingClaim: media-nfs-pvc

        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi

        networkPolicy:
          enabled: false

        securityContext:
          container:
            runAsNonRoot: false
            readOnlyRootFilesystem: false
            runAsUser: 0
            runAsGroup: 0
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
