apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sabnzbd
  namespace: media
spec:
  destination:
    namespace: media
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: sabnzbd
    repoURL: oci://tccr.io/truecharts
    targetRevision: 14.0.27
    helm:
      valueFiles:
        - ../../charts/values/sabnzbd-values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
