apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-apps
  namespace: media
spec:
  destination:
    namespace: media
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/brandongraves08/homelab.git
    targetRevision: HEAD
    path: manifests/direct
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
