apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-root
  namespace: media
spec:
  destination:
    namespace: media
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
      jsonnet: {}
      include:
        - "applications/*.yaml"
        - "routes/*.yaml"
    path: .
    repoURL: https://github.com/brandongraves08/homelab.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
