apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sabnzbd
  namespace: media
spec:
  port:
    targetPort: main
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: sabnzbd
    weight: 100
  wildcardPolicy: None
