apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - apps/plex.yaml
  - apps/radarr.yaml
  - apps/sonarr.yaml
  - apps/sabnzbd.yaml
  - routes/plex.yaml
  - routes/radarr.yaml
  - routes/sonarr.yaml
  - routes/sabnzbd.yaml
