apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argocd-redis
  namespace: argocd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  template:
    spec:
      volumes:
        - name: repos
          persistentVolumeClaim:
            claimName: argocd-repo-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-redis
  namespace: argocd
spec:
  template:
    spec:
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: argocd-redis
