apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-helm-repositories
  namespace: media
  labels:
    app.kubernetes.io/part-of: argocd
data:
  truecharts.yaml: |
    apiVersion: v1
    kind: Secret
    metadata:
      name: truecharts-repo
      namespace: media
      labels:
        argocd.argoproj.io/secret-type: repository
    stringData:
      name: truecharts
      url: https://charts.truecharts.org/
      type: helm
      enableOCI: "false"
