apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns
  namespace: openshift-gitops
spec:
  project: homelab-extras
  source:
    repoURL: https://github.com/brandongraves08/homelab.git
    targetRevision: HEAD
    path: openshift/extras/coredns
  destination:
    server: https://kubernetes.default.svc
    namespace: dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
