apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: openshift-gitops
spec:
  project: homelab-extras
  source:
    repoURL: https://github.com/brandongraves08/homelab.git
    path: openshift/extras/monitoring
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
