apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: openshift-gitops
spec:
  destination:
    namespace: media
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/brandongraves08/jellyfin-k8s.git
    targetRevision: main
    path: manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
