apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: homelab
  namespace: openshift-gitops
spec:
  description: Homelab media services
  destinations:
    - namespace: media
      server: https://kubernetes.default.svc
  sourceRepos:
    - '*'
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
