kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: route-manager
  namespace: media
rules:
- apiGroups: ["route.openshift.io"]
  resources: ["routes"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-route-manager
  namespace: media
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: route-manager
