apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-redis
  namespace: argocd
spec:
  template:
    spec:
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: argocd-redis-pvc
