apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: homelab-extras
  namespace: openshift-gitops
spec:
  description: Supporting services for homelab
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  sourceRepos:
    - '*'
