apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: dns
  labels:
    app: coredns

data:
  Corefile: |
    homelab.lan:53 {
        errors
        log
        rewrite name regex (.*)\.homelab\.lan {1}.apps.openshift.thelab.lan
        forward . 192.168.2.1
        cache 30
    }

    .:53 {
        errors
        log
        forward . 192.168.2.1
        cache 30
    }
