apiVersion: v1
kind: Service
metadata:
  name: coredns
  namespace: dns
spec:
  type: NodePort
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
      nodePort: 30553
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
      nodePort: 30554
  selector:
    app: coredns
