apiVersion: v1
kind: LimitRange
metadata:
  name: media-defaults
  namespace: media
spec:
  limits:
    - type: Container
      default:
        memory: 1Gi
        cpu: 500m
      defaultRequest:
        memory: 256Mi
        cpu: 100m
